// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMeK0h5rksNbm8lLQn4w_qYCJ8RUsdb2Q',
    appId: '1:535766920813:android:01536604c62aa6772a1964',
    messagingSenderId: '535766920813',
    projectId: 'pedalix-6cdf9',
    storageBucket: 'pedalix-6cdf9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHYmKLt04KWnsJCldNEDlJrasWQi1spxA',
    appId: '1:535766920813:ios:307e7ad4ef39da6a2a1964',
    messagingSenderId: '535766920813',
    projectId: 'pedalix-6cdf9',
    storageBucket: 'pedalix-6cdf9.appspot.com',
    androidClientId: '535766920813-9hg2reifegu51n193v776cro3lnvjiel.apps.googleusercontent.com',
    iosClientId: '535766920813-uv8l5qfltdcurft76b4mmtgisd8ci11p.apps.googleusercontent.com',
    iosBundleId: 'com.example.pedalixApp',
  );
}
