// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdDlJccq5HEe0TUM8mJPIYBGgpO8pttuw',
    appId: '1:492077384260:android:768725848bdcd06130f211',
    messagingSenderId: '492077384260',
    projectId: 'pedalix-30c8e',
    storageBucket: 'pedalix-30c8e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGeDc-9sMnRdE9G-uODow7AmH4IICcGfY',
    appId: '1:492077384260:ios:0978415f1167285630f211',
    messagingSenderId: '492077384260',
    projectId: 'pedalix-30c8e',
    storageBucket: 'pedalix-30c8e.appspot.com',
    androidClientId:
        '492077384260-6cqp6qcdl06m5ct1skfur00cgpv97di4.apps.googleusercontent.com',
    iosClientId:
        '492077384260-o304ps02b7p83evb94c5vj3kap7fmsfp.apps.googleusercontent.com',
    iosBundleId: 'com.example.pedalixApp',
  );
}
